#!/bin/sh

xset -dpms &
xset s off &
xset b off &
xset r rate 200 20 &
mstatus &
touchtog &
unclutter --idle 1 --ignore-buttons 1,2,3,4,5,6,7 --jitter 1 --start-hidden --hide-on-touch &
xbanish &
gentoo-pipewire-launcher &
clipmenud &
xsetroot -solid '#2e3440' &
xss-lock -- slock &
monitor &
exec dwm
