# Load environment settings from profile.env, which is created by
# env-update from the files in /etc/env.d
if [ -e /etc/profile.env ] ; then
	. /etc/profile.env
fi

source /etc/profile

# 077 would be more secure, but 022 is generally quite realistic
umask 022
bindkey -v
export KEYTIMEOUT=1

# Change cursor shape for different vi modes.
function zle-keymap-select () {
    case $KEYMAP in
        vicmd) echo -ne '\e[2 q';;      # block
        viins|main) echo -ne '\e[6 q';; # beam
    esac
}
zle -N zle-keymap-select
zle-line-init() {
    zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
    echo -ne "\e[6 q"
}
zle -N zle-line-init
echo -ne '\e[6 q' # Use beam shape cursor on startup.
preexec() { echo -ne '\e[6 q' ;} # Use beam shape cursor for each new prompt.

# Set up PATH depending on whether we're root or a normal user.
# There's no real reason to exclude sbin paths from the normal user,
# but it can make tab-completion easier when they aren't in the
# user's PATH to pollute the executable namespace.
#
# It is intentional in the following line to use || instead of -o.
# This way the evaluation can be short-circuited and calling whoami is
# avoided.
if [ "$EUID" = "0" ] || [ "$USER" = "root" ]; then
	# Check to make sure ROOTPATH is sane before we use it.
	# https://bugs.gentoo.org/656400
	if [ :${ROOTPATH}: == *:/usr/sbin:* ]; then
		PATH="${ROOTPATH}"
	fi
fi
export PATH
unset ROOTPATH

setopt interactive_comments
shopts=$-
for sh in /etc/profile.d/*.sh ; do
	[ -r "${sh}" ] && . "${sh}"
done
set -$shopts
unset sh shopts

# Extras
HISTSIZE=1000000000
SAVEHIST=1000000000
setopt extendedhistory histexpiredupsfirst histfindnodups histignoredups histignorespace histsavenodups histverify sharehistory

eval "$(dircolors -b)"

[ -f /usr/share/zsh/site-functions/zsh-autosuggestions.plugin.zsh ] && source /usr/share/zsh/site-functions/zsh-autosuggestions.plugin.zsh
[ -f /usr/share/zsh/site-functions/zsh-history-substring-search.plugin.zsh ] && source /usr/share/zsh/site-functions/zsh-history-substring-search.plugin.zsh
[ -f /usr/share/grc/grc.zsh ] && source /usr/share/grc/grc.zsh
for file in ~/.config/shell/*; do . "$file"; done

autoload -Uz compinit vcs_info
precmd() { vcs_info }
zstyle :compinstall filename '/home/amarakon/.zshrc'
zstyle ':vcs_info:git:*' formats ' %F{cyan}(%F{blue}git –%F{green} -%b%F{cyan})'
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
setopt prompt_subst

compinit -i

zle_highlight+=(paste:none)

{ [ "$(whoami)" = "root" ] && PROMPT='%B%F{blue}[%~${vcs_info_msg_0_}%F{blue}]%F{red}#%b%f '; } ||
{ PROMPT='%B%F{blue}[%~${vcs_info_msg_0_}%F{blue}]%b%F{green}$%b%f '; }
